services:
  postgres:
    container_name: postgres
    image: postgres:10
    environment:
      TZ: America/New_York
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    command: postgres -c 'max_connections=500'
    ports:
      - 5433:5432
    volumes:
      - db:/data/postgres
    networks:
      - crud
networks:
  crud:
    driver: bridge
volumes:
  db:
