services:
  postgres:
    container_name: postgres
    image: postgres:10
    environment:
      TZ: America/New_York
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    command: postgres -c 'max_connections=50'
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgres
    networks:
      - crud
  nginxproxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/conf.d/nginx-selfsigned.crt
      - ./nginx/nginx-selfsigned.key:/etc/nginx/conf.d/nginx-selfsigned.key
      - ./nginx/dhparam.pem:/etc/nginx/conf.d/dhparam.pem
    networks:
      - crud
  crud-spring:
    image: crud-spring:1.0.0
    ports:
      - 8081:8081
    depends_on:
      - postgres
    networks:
      - crud
networks:
  crud:
    driver: bridge
volumes:
  db:
